replicaCount: 2

container:
  name: pratik-container
  image: pratikbhusari10/hospital:v1.0.0
  containerPort: 5000

service:
  name: pratik-service
  port: 5000
  targetPort: 5000
  type: LoadBalancer

configMap:
  name: pratik-config
  data:
    APP_NAME: "Hospital-App"
    APP_PORT: "5000"

secret:
  name: pratik-secret
  type: Opaque
  data:
    DB_USER: YWRtaW4=
    DB_PASSWORD: YXRoYXJ2YUA3ODIz
